name: Upload steps to Vercel Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-steps:
    runs-on: ubuntu-latest
    environment: production
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build upload action
        run: pnpm action build

      - name: Migrate Database
        run: pnpm action migrate

      - name: Run upload action
        uses: ./apps/upload-action
        with:
          path: contents/**/*.md
